Connect to survey details API to get latest survey's questions list
minhnimble/android-surveys-list pull request #19
Opened 2020-10-24 09:16 UTC by minhnimble

https://github.com/minhnimble/android-surveys-list/projects/1#card-46083260

## What happened

When users are looking at the surveys list, they will be able to select and take a displayed survey or just look at that survey details and go back to the surveys list.

This is PR is for creating the logic for loading survey details with a list of questions that when user clicks `Start Survey` button, the app will have data to show the survey's questions list.
 
## Insight

- [x] Connect to survey details API to get latest survey's questions list
 
## Proof Of Work

Request survey details data successfully:
<img width="1400" alt="Screen Shot 2020-10-24 at 16 15 18" src="https://user-images.githubusercontent.com/70877098/97078155-33d9c980-1614-11eb-9f60-99068ebc1bd7.png">

2020-10-30 07:51 UTC, manh-t commented on app/src/main/java/co/nimblehq/data/model/Answer.kt
> +    @ColumnInfo(name = "display_order") val displayOrder: Int = -1
I see that you currently don't use `Answer` and `Question` in database. Are you going to add them into database in the future? 🙏

2020-10-30 07:51 UTC, manh-t commented on app/src/main/java/co/nimblehq/ui/screen/main/surveydetails/SurveyDetailsViewModel.kt
> +    val getSurveyDetailsError: Observable<Throwable>
I think `error` should not go with `get` 🤔 , or we can name it as `showError` and handle all errors here 🙏

2020-10-30 07:51 UTC, manh-t commented on data/src/main/java/co/nimblehq/data/api/parser/JsonReaderExtension.kt
> +        0
I'm not sure if we should handle `null` int value as `0`. If the data comes from API, I think we could mark them as nullable, including `nextStringOrEmpty`. How do you think?

2020-10-30 07:51 UTC, manh-t commented on data/src/main/java/co/nimblehq/data/api/parser/SurveyResponseParser.kt
>  package co.nimblehq.data.api.parser
The parser seems to be complicated 😅 
Can I ask that are you trying to parse json manually? 🙏   If so, I'm curious that how can you deal with this if the application is scalable? 😀

2020-10-30 07:51 UTC, manh-t commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +data class QuestionResponse(
IMO, we should create separate file for `QuestionReponse`. How do you think?

2020-10-30 07:51 UTC, manh-t commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +    @Json(name = "answers") var answers: List<AnswerResponse> = listOf()
should the values be nullable when getting data from API as I mentioned above? ☝️  We don't know that when will the API will return error case (eg. missing `display_order`), or data from API is the same as our default value 🤔

2020-10-30 07:52 UTC, manh-t commented
Sorry for the late review @minhnimble 🙇  I added some questions into the PR, please help me take a look at them 😁

2020-10-30 09:32 UTC, minhnimble commented on app/src/main/java/co/nimblehq/data/model/Answer.kt
> +    @ColumnInfo(name = "display_order") val displayOrder: Int = -1
nice question 🙏. About this part, when reading requirement, there is no mention about having to store Questions and Answers to database. Instead, the requirements ask us to implement questions list based on the API response:
`On the survey details page, the list of questions must be implemented based on the API response`

From my understanding, this would mean we have to get the latest survey questions list every time we start the survey, making sure we have latest questions data. As a result, I don't think we need to store questions and answers to cache 😊

2020-10-30 09:33 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/main/surveydetails/SurveyDetailsViewModel.kt
> +    val getSurveyDetailsError: Observable<Throwable>
oh okay, in this screen there is only one type of error, which is `GetSurveyDetailsError`, that is why I name it like this. I guess I will go with your suggestion for consistency 👍

2020-10-30 09:36 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/parser/JsonReaderExtension.kt
> +        0
oh, yeah I think it works for me too, let me update 👍

2020-10-30 09:42 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/parser/SurveyResponseParser.kt
>  package co.nimblehq.data.api.parser
previously I use automatic parsing but Trung asks me to flatten the response to only the objects we need, that is why I do this. My experiences with JSON parsing is not very much so this is the best I can do for now 😅 If you have any good suggestions for this case I would love learn more 💪

2020-10-30 09:44 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +data class QuestionResponse(
I think that is okay, will do it for clean separation

2020-10-30 09:48 UTC, minhnimble commented
Hi @manh-t, no worries, thank you for taking your time to review my branch 😍 taking a look now 🙏

2020-10-30 09:52 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +    @Json(name = "answers") var answers: List<AnswerResponse> = listOf()
I think providing default values is a much better approach, because eventually when you use the `response` in `ViewModel`, and then when the value is `null, we will also have to default it to something for the display to work. Maybe I can send the default assignments from `Response` layer to `Model` layer instead, and will update `Response` layer will nullable attributes for correctly reflecting API response data, what do you think? 😊

2020-10-30 09:53 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/parser/JsonReaderExtension.kt
> +        0
same [comment](https://github.com/minhnimble/android-surveys-list/pull/19#discussion_r514981427) here  🙏

2020-10-30 10:01 UTC, manh-t commented on app/src/main/java/co/nimblehq/data/model/Answer.kt
> +    @ColumnInfo(name = "display_order") val displayOrder: Int = -1
> As a result, I don't think we need to store questions and answers to cache

yes, I think so. We can display the error when there is no connectivity in case fetching the question. 
So shall we remove the annotations? (e.g `ColumnInfo`, `PrimaryKey`)😊

2020-10-30 10:07 UTC, manh-t commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +    @Json(name = "answers") var answers: List<AnswerResponse> = listOf()
> send the default assignments from Response layer to Model layer instead, and will update Response layer will nullable attributes for correctly reflecting API response data like your suggestion

@minhnimble yeah, I totally agree 🚀  Please go ahead

2020-10-30 10:10 UTC, minhnimble commented on app/src/main/java/co/nimblehq/data/model/Answer.kt
> +    @ColumnInfo(name = "display_order") val displayOrder: Int = -1
yeah sure, will update to remove, thanks 👍

2020-10-30 10:44 UTC, manh-t commented on data/src/main/java/co/nimblehq/data/api/parser/SurveyResponseParser.kt
>  package co.nimblehq.data.api.parser
From my understanding, we can create some base responses based on API response structure 🤔 
The base data always return
```json
// success:
{"data":{}}
// or 
{"data":[]}

//failed
{"error":{}}
```
So that we can create `BaseResponse` like this:
```kotlin
data class BaseResponse(
    @SerializedName("data") val data: Any?, // because the we are not sure that the data is object or list of object
    @SerializedName("error") val error: BaseErrorResponse?, // you can create the error response yourself easily
    @SerializedName("included") val included: List<??> // add if needed
)
```
I believe that the `data` object is consistency throughout app, it is:
```kotlin
data class DataResponse<T>(
    @SerializedName("id") val id: Any?, // I see that it's int/String sometimes in API
    @SerializedName("type") val type: String?,
    @SerializedName("attributes") val attribute: T   // T is our main thing
)
```

This nearly reach the target 😛 
We can cast the `data` in `BaseResponse` to `DataResponse<T>` or `List<DataResponse<T>>` according to the need.
This is my thought. Sorry if I missed something or my approach is wrong and hard to understand to you 😭  🙏

2020-11-02 07:01 UTC, manh-t commented on app/src/main/java/co/nimblehq/data/model/Question.kt
> +)
I think you missed this. We don't store Question or Answer to database anymore, so we could get rid of `@TypeConverters` here

2020-11-02 10:23 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/parser/SurveyResponseParser.kt
>  package co.nimblehq.data.api.parser
Hi @manh-t , I initially did this and understand your point, then Trung askes me to implement a custom Parser so that in the end it just returns the exact data we need as per comments from here `https://github.com/minhnimble/android-surveys-list/pull/12#discussion_r503842414` and here `https://github.com/minhnimble/android-surveys-list/pull/12#discussion_r504374424` 😅

2020-11-02 10:25 UTC, minhnimble commented on app/src/main/java/co/nimblehq/data/model/Question.kt
> +)
yeah you are right, let me get rid of them as well, sorry previously you just mention about `@ColumnInfo` `PrimaryKey` so I forget 🙏

2020-11-03 03:29 UTC, manh-t commented on data/src/main/java/co/nimblehq/data/api/parser/SurveyResponseParser.kt
>  package co.nimblehq.data.api.parser
so 🆗  🙏

2020-11-03 08:16 UTC, manh-t commented on app/src/main/java/co/nimblehq/ui/screen/main/surveys/SurveyItemUiModel.kt
> +fun Survey.toQuestionItemPagerUiModels() = questions.toQuestionItemPagerUiModels()
I think this function should be in `QuestionItemPagerUiModel.kt` 🙏

2020-11-03 08:16 UTC, manh-t commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
>      @Json(name = "surveys") var surveys: List<SurveyResponse> = listOf(),
should we apply nullable objects for `SurveyResponse` and `SurveysResponse` as well? 😅

2020-11-03 09:31 UTC, minhnimble commented on app/src/main/java/co/nimblehq/data/model/Question.kt
> +    answers = (answers ?: listOf()).toAnswers()
okay, will update 👍

2020-11-03 09:32 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
>      @Json(name = "surveys") var surveys: List<SurveyResponse> = listOf(),
yeah that should do for consistent 😊

2020-11-03 10:15 UTC, hoangnguyen92dn requested changes

2020-11-03 10:15 UTC, hoangnguyen92dn commented on data/src/main/java/co/nimblehq/data/api/parser/SurveyResponseParser.kt
> +                    "included" -> {
I got your idea about using `JsonAdapter` for flatten objects from `json api` with these attributes such as `included`, 'relationships',... (FYI: https://jsonapi.org/) So as I can see, we already added `banana` library as dependencies, just curious why don't we use `banana` for parsing `json api` like the way The1 implemented rather than doing manually here. (Refer: `ResourceAdapterProvider` from The1 Android project and usage of `JsonApi` annotation)

Thanks @luongvo for explanation about Moshi and Banana to me 🙏

2020-11-03 10:38 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/parser/SurveyResponseParser.kt
> +                    "included" -> {
Yeah, originally I spent 2 days to investigate how we can use a Parser to flatten objects with` https://jsonapi.org/` `Moshi` but unfortunately, I could not make the parser works correct to `jsonapi` style previously. As a result, I have to do it this way. 

The issue I have previously is that, The1 response object is already have all params grouped inside `attributes`, but here in the test project api, the `id` is outside of `attributes` object so how can you flatten `id` from outside `attributes` and other `attributes` keys into one single flatten object?

2020-11-03 10:39 UTC, minhnimble commented on app/src/main/java/co/nimblehq/data/model/Answer.kt
> +    text = text ?: "",
got it

2020-11-03 10:39 UTC, minhnimble commented on app/src/main/java/co/nimblehq/data/model/Question.kt
> +    text = text ?: "",
got it

2020-11-03 10:39 UTC, minhnimble commented on app/src/main/java/co/nimblehq/usecase/survey/LoadSurveyDetailsSingleUseCase.kt
> +    )
oh nice catch, forget about this 👍

2020-11-03 10:40 UTC, minhnimble commented on app/src/main/java/co/nimblehq/data/model/Answer.kt
> +    val displayOrder: Int = -1
I think you are conflicting with Manh's comment, we should make `Response` object nullable and provide default values in model/uimodel layer

2020-11-04 03:06 UTC, hoangnguyen92dn commented on app/src/main/java/co/nimblehq/data/model/Answer.kt
> +    val displayOrder: Int = -1
@manh-t I am not sure why you suggested to update to define default value from model/uimodel, we should define default value from response layer because the response from api could changed sometimes so adding default value for handle case response missing some expected elements. Can you please explain your idea?

2020-11-04 03:07 UTC, hoangnguyen92dn commented on app/src/main/java/co/nimblehq/data/model/Answer.kt
> +    val displayOrder: Int = -1
@manh-t I am not sure why you suggested to update to define default value from model/uimodel, we should define default value from response layer because the response from api could changed sometimes so adding default value for handle case response missing some expected elements. Can you please explain your idea?

2020-11-04 03:08 UTC, hoangnguyen92dn commented on data/src/main/java/co/nimblehq/data/api/parser/SurveyResponseParser.kt
> +                    "included" -> {
Yeah. I am worry about new coming feature with new api response so you still need to parse response manually, it would take unnecessary effort on that.

2020-11-04 07:20 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/parser/SurveyResponseParser.kt
> +                    "included" -> {
yeah totally understand your point, will check this

2020-11-04 07:30 UTC, manh-t commented on app/src/main/java/co/nimblehq/data/model/Answer.kt
> +    val displayOrder: Int = -1
@hoangnguyen92dn We can define default value anywhere, but I think it's better if @minhnimble can know our formatting from the beginning (nullable at Response layer, then define value in Model layer), we can handle case response missing some expected elements in Model layer as well 😁

2020-11-04 09:10 UTC, manh-t commented on app/src/main/java/co/nimblehq/ui/screen/main/surveydetails/QuestionItemPagerUiModel.kt
> +    val answers: List<AnswerItemUiModel> = listOf()
I think you don't need to specify the default values for UiModel since we get them from Model layer 🤔

2020-11-04 09:10 UTC, manh-t commented on app/src/main/java/co/nimblehq/ui/screen/main/surveydetails/SurveyDetailsViewModel.kt
> +    private val _getSurveyDetailsError = PublishSubject.create<Throwable>()
Should it be `_showError`?

2020-11-04 09:24 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/main/surveydetails/QuestionItemPagerUiModel.kt
> +    val answers: List<AnswerItemUiModel> = listOf()
sure, let me update 👍

2020-11-04 09:25 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/main/surveydetails/SurveyDetailsViewModel.kt
> +    private val _getSurveyDetailsError = PublishSubject.create<Throwable>()
nice catch, I missed this place, let me update 👌

2020-11-04 09:47 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/main/surveydetails/QuestionItemPagerUiModel.kt
> +    val answers: List<AnswerItemUiModel> = listOf()
okay that makes sense, let me update

2020-11-05 08:20 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/parser/SurveyResponseParser.kt
> +                    "included" -> {
Implemented the Moshi parser with Banana for JsonApi

2020-11-05 11:22 UTC, hoangnguyen92dn commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +        return if (hasQuestion) questions else null
We already applied `Moshi` and `Banana` so I believe we could get rid of this.

2020-11-06 03:54 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/providers/ResourceAdapterProvider.kt
> +                AnswerResponse::class.java
yep we don't need it with the current implementation, I just leave it there for backing up so I can revert to use the old parsing way. Will remove

2020-11-06 03:55 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/main/surveys/SurveysViewModel.kt
> +                }
I like bracket style more, but this should be on 1 line, thanks for spotting 👍

2020-11-06 03:55 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/response/survey/QuestionResponse.kt
> +    fun getAnswerResponses(): List<AnswerResponse>? {
will update 👍

2020-11-06 03:56 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +        return if (hasQuestion) questions else null
previously I have null issues when just do `questions?.get(document)` so I have to do this. Let me check

2020-11-06 09:04 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +        return if (hasQuestion) questions else null
Added a better check for this case, you can take a look now 🙏

2020-11-06 10:17 UTC, hoangnguyen92dn reviewed
@mikepham1011 @minhnimble Just one comment left 🚀

2020-11-06 10:17 UTC, hoangnguyen92dn commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +    }
Same here.

2020-11-06 10:17 UTC, hoangnguyen92dn commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +        return if (questions?.firstOrNull() != null) questions else null
As I can see, you have to validate this because of using same response for survey list and survey details, can you please create separate response and get rid of unnecessary validate here?

2020-11-06 10:21 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +        return if (questions?.firstOrNull() != null) questions else null
oh understand your point, yeah I can definitely separate it, let me update 👍

2020-11-06 10:49 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +        return if (questions?.firstOrNull() != null) questions else null
I created two different responses but it triggers a crash issue, can't update ^^!

![Screen Shot 2020-11-06 at 17 48 01](https://user-images.githubusercontent.com/70877098/98357836-5f1ed880-2058-11eb-85e9-3db5874addc9.png)

2020-11-06 11:24 UTC, hoangnguyen92dn commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +        return if (questions?.firstOrNull() != null) questions else null
Ahha. Gotta. Just double checked the survey details response, you need to update the current response class. We just need the list of `question` and `answer`, so that mean we could update to use `QuestionResponse` as the response for survey details endpoint, does it make sense to you? If so, can you please try with this solution?

2020-11-06 11:38 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +        return if (questions?.firstOrNull() != null) questions else null
okay let me try, if it works it is really nice lol

2020-11-06 11:53 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +        return if (questions?.firstOrNull() != null) questions else null
Hi @hoangnguyen92dn, I don't think it works :(( . When I tried to change the service to just provide the list of question responses only for loading survey details like this:
![Screen Shot 2020-11-06 at 18 48 59](https://user-images.githubusercontent.com/70877098/98363099-fee06480-2060-11eb-8d2f-e24452d95a37.png)

It still parse the object as type `survey` and the array of questions is now null:
![Screen Shot 2020-11-06 at 18 48 48](https://user-images.githubusercontent.com/70877098/98363200-2b947c00-2061-11eb-85ca-486656bb2772.png)

2020-11-09 05:23 UTC, hoangnguyen92dn commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +        return if (questions?.firstOrNull() != null) questions else null
Hi @minhnimble Just did a small update and it's working as expected from my side, we need to consolidate the response classes and properties a little bit here:

1. `api/v1/surveys`

This endpoint returns `List<SurveyReponse>` with necessary data such as: title, description, cover image url

2. `/api/v1/surveys/{surveyId}`

This endpoint returns `List<SurveyDetailsResponse>` (SurveyDetailsResponse is the new class I created), we could handle to get the list of questions, answers from this endpoint.

Could you please try again from your side?

FYI: This is debugging result for temporary updated from my side

![image](https://user-images.githubusercontent.com/6950766/98503068-4136bb00-2286-11eb-8c98-ba6669473362.png)

2020-11-09 06:07 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyResponse.kt
> +        return if (questions?.firstOrNull() != null) questions else null
oh,thanks for the screenshots, it is clearer now, previously I thought you want to return the array of questions directly in the Service layer, but it should be in the Repository layer. Let me update

2020-11-09 08:11 UTC, hoangnguyen92dn reviewed
In case we need to build for production with `minify` mode enabled, the app would be failed on launch because at least you are missing some configuration part on proguards for `banana` library. Please check and update if needed.

2020-11-09 08:11 UTC, hoangnguyen92dn commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyBasicResponse.kt
> +            Operators.moshi.adapter(SurveysMetaResponse::class.java)
Hmm. Imo, define adapter for parsing data from response layer. Could we update to get rid of this? I guess we could define parent response class with `surveys` and `meta` 🤔

2020-11-09 08:27 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyDetailsResponse.kt
> +
oh nice catch, let me update 👍

2020-11-09 08:27 UTC, minhnimble commented on app/src/main/java/co/nimblehq/data/model/Survey.kt
> +)
yep you are right, can remove I believe, let me check

2020-11-09 08:32 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyBasicResponse.kt
> +            Operators.moshi.adapter(SurveysMetaResponse::class.java)
This is the technique used in `The1` since we are using the JsonApi parser, not sure the technique you mention means going back to manual parsing? 🤔

2020-11-10 03:18 UTC, hoangnguyen92dn commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyBasicResponse.kt
> +            Operators.moshi.adapter(SurveysMetaResponse::class.java)
Hmm. My idea is get rid of the moshi adapter from Response class and define in the Factory same as `QuestionResponse` and `AnwserResponse`. Actually I am still ok with the current one solution, just wondering if we could revamp a little bit here.

2020-11-10 03:18 UTC, hoangnguyen92dn approved these changes
LGTM

2020-11-10 04:11 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/response/survey/SurveyBasicResponse.kt
> +            Operators.moshi.adapter(SurveysMetaResponse::class.java)
hmm, understood your point, I did experimenting a bit but it seems to not parse correctly. Not really sure how to do it right. Will definitely take a look again when we have more time 👌

2020-11-11 06:58 UTC, manh-t approved these changes
the PR looks better 💦  just a minor comment left 🚀

2020-11-11 06:58 UTC, manh-t commented on app/src/main/java/co/nimblehq/ui/screen/main/surveydetails/SurveyDetailsViewModel.kt
> +            .subscribeBy (
formatting 😳

2020-11-11 07:12 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/main/surveydetails/SurveyDetailsViewModel.kt
> +            .subscribeBy (
really nice catch, I missed it somehow 🤣 , will fix it 👍

2020-11-11 07:29 UTC, merged