[TASK-4] [Feature] As a user, I can automatically enter the home dashboard once logged in
minhnimble/android-surveys-list pull request #8
Opened 2020-10-07 05:34 UTC by minhnimble

https://github.com/minhnimble/android-surveys-list/projects/1#card-46081236

## What happened

When users are logged in previously, they will be redirected to the home dashboard without having to enter login credentials again. If the session is expired, users will see the login screen as usual.
 
## Insight

**Acceptance Criteria**
- [x] Implement auto-refresh token logic flow
- [x] Implement token expired logic flow
- [x] Connect to refresh token API
 
## Proof Of Work

![Screen Recording 2020-10-07 at 11 45 59](https://user-images.githubusercontent.com/70877098/95290854-7a9b9580-0898-11eb-8cb1-533579957ce0.gif)

2020-10-07 08:04 UTC, hoangnguyen92dn requested changes
@minhnimble Please add UnitTest for new code changes (UnitTest, ViewModel, ...) 🙏  It would be better if UnitTest included in each PR 😅

2020-10-07 08:04 UTC, hoangnguyen92dn commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/signin/SignInViewModel.kt
> +    private val _loginError = PublishSubject.create<Throwable>()
`_error` could be more common usage, what happens if we are going to handle not only `signIn` here? And the variable name should be consistency with class name `SignIn` vs `Login`.

2020-10-07 09:22 UTC, minhnimble commented
> @minhnimble Please add UnitTest for new code changes (UnitTest, ViewModel, ...) 🙏 It would be better if UnitTest included in each PR 😅

I am creating a separate PR for unit test, not put everything in one PR 😅

2020-10-07 09:23 UTC, minhnimble commented on app/src/main/java/co/nimblehq/data/model/AuthData.kt
> +fun OAuthResponse.toAuthData() = with(this.data.attributes) {
ohhh, nice catch, thanks for letting me know, will fix it 😅

2020-10-07 09:28 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/main/MainViewModel.kt
> +    fun checkSession(): Single<Boolean> {
oh nice catch, will fix it

2020-10-07 09:29 UTC, minhnimble commented on app/src/main/java/co/nimblehq/usecase/session/RefreshTokenIfNeededSingleUseCase.kt
> +) : SingleUseCase<RefreshTokenIfNeededSingleUseCase.Input, AuthData>(rxSchedulerProvider.io(), rxSchedulerProvider.io(), ::RefreshTokenError) {
oh I missed this one, let me update

2020-10-07 09:30 UTC, minhnimble commented on app/src/test/java/co/nimblehq/usecase/session/LoginByPasswordSingleUseCaseTest.kt
> +        ) doReturn Single.just(AuthData("",0,0,"",""))
oh I thought for default value we can do this, let me update

2020-10-07 09:33 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/OnboardingViewModel.kt
> +            }
I want to show a simple error as "Server error" so a Unit is provided. Not really see a need to show a long server error message to the user, for debugging purpose we can still see our console log 😊

2020-10-07 09:34 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/OnboardingActivity.kt
> +            .subscribe { displayError(Throwable("Server error")) }
oh let me create a string for it, thanks for spotting

2020-10-07 09:36 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/main/MainActivity.kt
> +        }
hmm, this technique is used by The1 Android, I think it is fine to keep, why are you against it? any reason? 🤔

2020-10-07 09:37 UTC, minhnimble commented on app/src/main/java/co/nimblehq/usecase/session/RefreshTokenIfNeededSingleUseCase.kt
> +    )
oh okay, agree with you on this

2020-10-07 09:46 UTC, hoangnguyen92dn commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/OnboardingViewModel.kt
> +            }
How about add `xxxError` to `Throwable.userReadableMessage` from `ThrowableExtension`?

2020-10-07 09:48 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/OnboardingViewModel.kt
> +            }
oh got it

2020-10-07 09:50 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/signin/SignInFragment.kt
> +            .bindForDisposable()
yeah can you give me some examples about your idea

2020-10-07 09:52 UTC, hoangnguyen92dn commented on app/src/main/java/co/nimblehq/ui/screen/main/MainActivity.kt
> +        }
Please be careful with `blockingGet()`, it will block current thread until the stream receive a success value, so that's why I'd suggest to use `subscribe`. We could use `blockingGet()` when we have noway to add stream to `Disposable`

2020-10-07 09:52 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/signin/SignInViewModel.kt
> +    private val _loginError = PublishSubject.create<Throwable>()
right now we are using it for login purpose only, so there is no point in create a generic error at the moment, we can definitely update when there are more types of error in the future

2020-10-07 09:53 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/signin/SignInViewModel.kt
> +    private val _loginError = PublishSubject.create<Throwable>()
about name consistency yeah I will update it

2020-10-07 09:53 UTC, minhnimble commented on app/src/main/java/co/nimblehq/usecase/session/GetUserTokenSingleUseCase.kt
> +) : SingleUseCase<Unit, AuthData>(rxSchedulerProvider.io(), rxSchedulerProvider.io(), ::Ignored) {
got it

2020-10-07 09:54 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/service/auth/AuthService.kt
> +    ): Flowable<OAuthResponse>
yeah let me apply it

2020-10-07 09:54 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/main/MainViewModel.kt
> +            .map(UpdateTokenCompletableUseCase::Input)
yup, will update

2020-10-07 09:57 UTC, hoangnguyen92dn commented
@minhnimble UnitTest included would be nice for reviewers and we could update the code to testable if needed earlier.

2020-10-07 10:05 UTC, manh-t commented on app/src/main/java/co/nimblehq/ui/screen/main/MainActivity.kt
> +        }
@minhnimble I notice that you have checked session in Onboarding screen. Any reason why we recheck here? 🙏

2020-10-07 10:05 UTC, manh-t commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/OnboardingViewModel.kt
> +            }
I'm wondering that shall we show error message when refreshing token failed here? Could it makes more sense if we return to login screen instead of show error message? 🙏

2020-10-07 10:07 UTC, hoangnguyen92dn commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/signin/SignInFragment.kt
> +            .bindForDisposable()
1. Create NavigationEvent

```
sealed class NavigationEvent {

    sealed class Splash : NavigationEvent() {
        object Home : Splash()
    }
}
```

2. From ViewModel

`    private val _navigator = PublishSubject.create<NavigationEvent>()`

3. Emit navigation event from ViewModel

```
                    _navigator.onNext(
                        NavigationEvent.Splash.Home()
                    )
```

4. Subscribe from Fragment

```
        viewModel.navigator
            .subscribe { event -> 
                when (event) {
                    is NavigationEvent.Splash.Home -> // Navigate to Home
                }
            }
            .bindForDisposable()
```

2020-10-07 10:19 UTC, manh-t commented on app/src/main/java/co/nimblehq/data/authenticator/TokenRefresher.kt
> +    fun refreshToken(token: String): Single<AuthData>
Can I know the idea behind this please? I haven't seen its using in somewhere 🙏

2020-10-07 10:23 UTC, hoangnguyen92dn commented on app/src/main/java/co/nimblehq/ui/screen/main/MainActivity.kt
> +        }
@minhnimble I think The1 devs want to use `blockingGet()` for stopping downstream code until `checkSession` finished. So as Manh's comment, just curious about the logic to validate `checkSession` on both OnBoarding and Main 🤔  and we could remove `return` in `if` block.

2020-10-07 10:43 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/signin/SignInFragment.kt
>              .subscribe(::bindLoginStatus)
yep we can definitely use `displayError`, let me update

2020-10-07 10:46 UTC, minhnimble commented on app/src/main/java/co/nimblehq/data/authenticator/TokenRefresher.kt
> +    fun refreshToken(token: String): Single<AuthData>
the AuthRepository conforms this for handling token refreshing in Onboarding Activity and Main Activity, let me update it a bit 👍

2020-10-07 10:54 UTC, minhnimble commented
> @minhnimble I notice that you have checked session in Onboarding screen. Any reason why we recheck here? 🙏

oh this is for kicking user out of this Home screen back to Onboarding screen to sign in again if that user has an expired token and the app cannot refresh it using refresh token api. The1 Android also has this logic in its Main screen 🙏

> I'm wondering that shall we show error message when refreshing token failed here? Could it makes more sense if we return to login screen instead of show error message? 🙏

we are at Onboarding screen (Login screen) already, so how can we return to it again, I don't get your point 🤔

2020-10-07 11:19 UTC, manh-t commented
> oh this is for kicking user out of this Home screen back to Onboarding screen to sign in again if that user has an expired token and the app cannot refresh it using refresh token api. The1 Android also has this logic in its Main screen 🙏.
I strongly believe this is for time sensitive situation when users still has a local valid token in Onboarding screen but when it reaches Home screen, it becomes invalid and at that time, the application can't connect to refresh token api and we have to kick that user back to Onboarding screen

I understand what you mean, but in The1 project, it is definitely different case because we dont have Splash screen in The1. 
About your case, we already checked it in Onboarding, why do we need to check it again? Seems it is duplicated 🤔  How do you think? 🙏 

> we are at Onboarding screen (Login screen) already, so how can we return to it again, I don't get your point 🤔

Ah I see, I think we can display a general message like `Session expired. Please login again.` for that.

2020-10-07 11:23 UTC, minhnimble commented
> I understand what you mean, but in The1 project, it is definitely different case because we dont have Splash screen in The1.
> About your case, we already checked it in Onboarding, why do we need to check it again? Seems it is duplicated 🤔 How do you think? 🙏
🙏
Hmm, let me run more testings on this case to check if it is really needed, thanks for spotting out 

> Ah I see, I think we can display a general message like `Session expired. Please login again.` for that.

That would also make sense, yeah definitely will update to that message, nice catch 👍

2020-10-08 03:00 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/main/MainActivity.kt
> +        }
hmm, after deeper testing, I think it is okay to the check session at Main, let me remove 👍

> and we could remove `return` in `if` block.

In the future we might add more logic code below this check, so leaving `return` here is for future usage

2020-10-08 03:02 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/signin/SignInFragment.kt
> +            .bindForDisposable()
thanks for your detail explanation, I would love to try this 👍

2020-10-08 03:04 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/OnboardingViewModel.kt
> +            }
> I'm wondering that shall we show error message when refreshing token failed here? Could it makes more sense if we return to login screen instead of show error message? 🙏

oh we are at login screen and checking if the token is valid or not, can't back to login screen anymore 😅

2020-10-08 03:19 UTC, hoangnguyen92dn commented on app/src/main/java/co/nimblehq/ui/screen/main/MainActivity.kt
> +        }
Hi @minhnimble, we need your clarification about `checkSession` and `refreshToken` flow here. As far as I understand, `checkSession` on OnBoarding screen make more sense rather than Main screen.

2020-10-08 03:21 UTC, hoangnguyen92dn commented
@minhnimble Please resolve all comments in this PR 🙏  Create new PR for fixing comments is unnecessary 😅

2020-10-08 03:25 UTC, minhnimble commented
> @minhnimble Please resolve all comments in this PR 🙏 Create new PR for fixing comments is unnecessary 😅

yeah I know, the previous PR was huge so I have to split, this one is a small PR and thus I will definitely put related fixes in here 👍

2020-10-08 03:32 UTC, sleepylee commented
@hoangnguyen92dn @manh-t there are few things I'd like to address here:
- The review should **not** be opinionated, I understood that we are having a few differences in our architecture in different projects; this should not be taken as the only source of truth and enforce the others. It will create a mixed weird hotpot and the project will never be done. The target here for the review is:
  - We should make sure that @minhnimble will not make any serious/common mistake
  - All the codes should be testable, architecture solution can be different, but as long as he can test his codes, we shouldn't police his solution. This suppresses the other's idea of expressing their own creativity, which is NOT good.
  
By complying with these guidelines to review, we can move at a faster pace and learn from the other's perspective as well. This is usually the way we review the assignment of a candidate if you guys still remember how I and @luongvo did the review with you before 🙏  Let me know if you have any questions.

2020-10-08 03:42 UTC, sleepylee commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/OnboardingActivity.kt
> +        if (viewModel.checkSession().blockingGet()) {
perhaps just subscribe and react accordingly:
```
viewModel.checkSession()
       .subscribeBy { loggedIn -> 
             onSuccess = { if (loggedIn) navigator.navigateToMainActivity()  else /* you should handle this */ }
             onError =  { ??? }
       }

2020-10-08 03:47 UTC, sleepylee commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/OnboardingViewModel.kt
> +            .doOnError(_refreshTokenError::onNext)
wondering if we can subscribe at the downstream (on the View) and get rid of this `doOnError` and `_refreshTokenError` ? 🤔  basically the idea is to keep this error to be handled by the `onError` of the subscriber, it's a part of rxjava is to handle success/error at the subscribe block and avoid the side effect method if possible. How do you think?

2020-10-08 03:48 UTC, hoangnguyen92dn commented on data/src/main/java/co/nimblehq/data/api/service/auth/AuthService.kt
> +    ): Flowable<OAuthResponse>
From my previous comment, my idea is remove `refreshToken`, and we could rename current `loginByPasswordWithEmail` to `authenticate` for common usage (Login and Refresh token)

Ex:

```
    @POST("/api/v1/oauth/token")
    fun authenticate(
        @Body request: OAuthRequest
    ): Flowable<OAuthResponse>
```

2020-10-08 03:48 UTC, hoangnguyen92dn commented on data/src/main/java/co/nimblehq/data/api/request/OAuthRequest.kt
> +	data class LoginByPasswordWithEmailRequest(
Not a big deal but suffix `Request` seems duplicated from parent

2020-10-08 03:48 UTC, hoangnguyen92dn commented on app/src/main/java/co/nimblehq/usecase/session/RefreshTokenIfNeededSingleUseCase.kt
> +class RefreshTokenIfNeededSingleUseCase @Inject constructor(
Please add UnitTest for this UseCase

2020-10-08 03:48 UTC, hoangnguyen92dn commented on app/src/main/java/co/nimblehq/usecase/session/GetUserTokenSingleUseCase.kt
> +class GetUserTokenSingleUseCase @Inject constructor(
Lack of UnitTest please 🙏

2020-10-08 03:48 UTC, hoangnguyen92dn commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/signin/SignInViewModel.kt
> +        get() = _navigator
Any test case for navigator?

2020-10-08 03:51 UTC, sleepylee commented on data/src/main/java/co/nimblehq/data/api/request/OAuthRequest.kt
> +		@SerializedName("grant_type") val grantType: String,
not sure if this indentation is correct 😓  could you please recheck?

2020-10-08 03:51 UTC, sleepylee commented on app/src/main/java/co/nimblehq/data/model/AuthData.kt
> +		expiresIn,
not sure if this indentation is correct 😓  could you please recheck?

2020-10-08 03:54 UTC, minhnimble commented on app/src/main/java/co/nimblehq/data/model/AuthData.kt
> +		expiresIn,
it is correct in AS, I think the Git code display has some issues here 😅
![Screen Shot 2020-10-08 at 10 54 08](https://user-images.githubusercontent.com/70877098/95413038-9f554300-0954-11eb-93af-f402d879c80f.png)

2020-10-08 03:55 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/request/OAuthRequest.kt
> +		@SerializedName("grant_type") val grantType: String,
it is correct in AS, same issue 😅

![Screen Shot 2020-10-08 at 10 55 00](https://user-images.githubusercontent.com/70877098/95413102-c875d380-0954-11eb-9657-6f188901317a.png)

2020-10-08 03:56 UTC, hoangnguyen92dn commented on app/src/main/java/co/nimblehq/data/model/AuthData.kt
> +		expiresIn,
@minhnimble The indentation from your screenshot is tab instead of space. So that's why it looks weird on Github.

2020-10-08 04:05 UTC, hoangnguyen92dn commented on app/src/main/java/co/nimblehq/data/model/AuthData.kt
> +		expiresIn,
@minhnimble From our Compass 😅 

> - Indentation:
> Only using spaces * never tabs.

https://compass.nimblehq.co/development/code-conventions/kotlin/#formatting

2020-10-08 04:10 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/service/auth/AuthService.kt
> +    ): Flowable<OAuthResponse>
oh I understand your idea now, it is a bit blurry before, I thought it was just for refactoring purpose

2020-10-08 04:13 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/signin/SignInViewModel.kt
> +        get() = _navigator
test is separated in another PR, need to finalize all the logic code first before adding test since they are constantly changing

2020-10-08 04:14 UTC, minhnimble commented on app/src/main/java/co/nimblehq/usecase/session/GetUserTokenSingleUseCase.kt
> +class GetUserTokenSingleUseCase @Inject constructor(
test is added in another branch, will push that branch up after this PR

2020-10-08 04:14 UTC, minhnimble commented on app/src/main/java/co/nimblehq/usecase/session/RefreshTokenIfNeededSingleUseCase.kt
> +class RefreshTokenIfNeededSingleUseCase @Inject constructor(
test is added in another branch, will push that branch up after this PR

2020-10-08 04:14 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/request/OAuthRequest.kt
> +	data class LoginByPasswordWithEmailRequest(
agree with you on this, can remove Request suffix

2020-10-08 04:21 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/OnboardingActivity.kt
> +        if (viewModel.checkSession().blockingGet()) {
oh the goal is to get the token refreshed before rendering the Onboarding Activity (showing SignIn Screen). As you have already known, there is a welcome animation for showing login screen. If we don't use blockingGet() here, users will see a brief moment of the animation, then if token is expired and then refreshed by the api successfully, it will suddenly jump to the Main Screen while animately showing the SignIn Screen. That is why we need it

2020-10-08 04:23 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/OnboardingViewModel.kt
> +            .doOnError(_refreshTokenError::onNext)
I think we can definitely do it, let me check and apply it, there was some references in The1 still use this way so I think it is applicable 🙏

2020-10-08 04:36 UTC, minhnimble commented on app/src/main/java/co/nimblehq/data/model/AuthData.kt
> +		expiresIn,
oh, I am not aware of this, let me config my AS again 😅

2020-10-08 05:32 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/OnboardingActivity.kt
> +        if (viewModel.checkSession().blockingGet()) {
or I need to update the logic to delay the animation a bit

2020-10-08 06:09 UTC, minhnimble commented
> From my previous comment, my idea is remove `refreshToken`, and we could rename current `loginByPasswordWithEmail` to `authenticate` for common usage (Login and Refresh token)
>
>Ex:
>
>```
>    @POST("/api/v1/oauth/token")
>    fun authenticate(
>        @Body request: OAuthRequest
>    ): Flowable<OAuthResponse>
>```

I am not sure if you use this technique before but using the sealed class OAuthRequest like this doesn't work since Retrofit doesn't recognize the request class you paste in, it just consider checking the sealed OAuthRequest class and since there is no property, it send an empty request up. Can you share the full working implementation?

2020-10-08 06:23 UTC, minhnimble commented on data/src/main/java/co/nimblehq/data/api/service/auth/AuthService.kt
> +    ): Flowable<OAuthResponse>
@hoangnguyen92dn, I am not sure if you use this technique before but using the sealed class OAuthRequest like this doesn't work since Retrofit doesn't recognize the request class you paste in, it just consider checking the sealed OAuthRequest class and since there is no property, it send an empty request up. Can you share the full working implementation?

2020-10-08 06:26 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/OnboardingActivity.kt
> +        if (viewModel.checkSession().blockingGet()) {
for now we will have a crash issue because the view is being animated and then the onSuccess subscription kicks in that send the user to Main Screen

2020-10-08 06:48 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/main/MainActivity.kt
> +        }
yeah, already remove `checkSession` flow in Main Screen

2020-10-08 09:21 UTC, hoangnguyen92dn approved these changes
Please use `git squash` to reduce the number of commits for the next PRs.

2020-10-08 09:21 UTC, hoangnguyen92dn commented on app/src/main/java/co/nimblehq/event/NavigationEvent.kt
> +	}
Please update this format in next PR

2020-10-08 09:45 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/signin/SignInViewModel.kt
> +        get() = _navigator
you can find the tests in this branch: https://github.com/minhnimble/android-surveys-list/pull/9🙏

2020-10-08 09:45 UTC, minhnimble commented on app/src/main/java/co/nimblehq/usecase/session/GetUserTokenSingleUseCase.kt
> +class GetUserTokenSingleUseCase @Inject constructor(
you can find the tests in this PR: #9 🙏

2020-10-08 09:45 UTC, minhnimble commented on app/src/main/java/co/nimblehq/usecase/session/RefreshTokenIfNeededSingleUseCase.kt
> +class RefreshTokenIfNeededSingleUseCase @Inject constructor(
you can find the tests in this PR: #9 🙏

2020-10-08 09:47 UTC, minhnimble commented on app/src/main/java/co/nimblehq/event/NavigationEvent.kt
> +	}
got it, thanks for catching 👍

2020-10-08 09:47 UTC, minhnimble commented
> Please use `git squash` to reduce the number of commits for the next PRs.

yes sure 👍

2020-10-08 09:56 UTC, manh-t approved these changes

2020-10-08 10:04 UTC, minhnimble commented on app/src/main/java/co/nimblehq/ui/screen/onboarding/OnboardingActivity.kt
> +        if (viewModel.checkSession().blockingGet()) {
Reworked the flow to remove `blockingGet()` usage

2020-10-09 07:16 UTC, merged